<?php

// The Installer module must be available before package discovery so a fresh
// release can boot its first-run routes even before Composer's merged module
// autoload metadata has been regenerated by the deployment process.
spl_autoload_register(static function (string $class): void {
    $prefix = 'Modules\\Installer\\';
    if (! str_starts_with($class, $prefix)) {
        return;
    }

    $path = dirname(__DIR__).'/Modules/Installer/app/'.str_replace('\\', '/', substr($class, strlen($prefix))).'.php';
    if (is_file($path)) {
        require_once $path;
    }
});

use App\Http\Middleware\EnsureAppKey;
use App\Http\Middleware\AuthCheck;
use App\Http\Middleware\Authenticate;
use App\Http\Middleware\DenyDuringDemo;
use App\Http\Middleware\EncryptCookies;
use App\Http\Middleware\EnsurePermission;
use App\Http\Middleware\PreventRequestsDuringMaintenance;
use App\Http\Middleware\RedirectIfAuthenticated;
use App\Http\Middleware\SetLocale;
use App\Http\Middleware\TrimStrings;
use App\Http\Middleware\TrustProxies;
use App\Http\Middleware\ValidateSignature;
use App\Http\Middleware\VerifyCsrfToken;
use App\Http\Middleware\XSS;
use Illuminate\Auth\Middleware\AuthenticateWithBasicAuth;
use Illuminate\Auth\Middleware\Authorize;
use Illuminate\Auth\Middleware\EnsureEmailIsVerified;
use Illuminate\Auth\Middleware\RequirePassword;
use Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse;
use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull;
use Illuminate\Foundation\Http\Middleware\HandlePrecognitiveRequests;
use Illuminate\Foundation\Http\Middleware\ValidatePostSize;
use Illuminate\Http\Middleware\AddLinkHeadersForPreloadedAssets;
use Illuminate\Http\Middleware\HandleCors;
use Illuminate\Http\Middleware\SetCacheHeaders;
use Illuminate\Routing\Middleware\SubstituteBindings;
use Illuminate\Routing\Middleware\ThrottleRequests;
use Illuminate\Session\Middleware\AuthenticateSession;
use Illuminate\Session\Middleware\StartSession;
use Illuminate\View\Middleware\ShareErrorsFromSession;
use Modules\Installer\Http\Middleware\EnsureApplicationKey;
use Modules\Installer\Http\Middleware\EnsureInstalled;
use Modules\Installer\Http\Middleware\RedirectIfInstalled;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: [
            __DIR__.'/../routes/web.php',
            __DIR__.'/../routes/auth.php',
            __DIR__.'/../routes/setting.php',
            __DIR__.'/../routes/user.php',
        ],
        api: __DIR__.'/../routes/api.php',
        commands: __DIR__.'/../routes/console.php',
        channels: __DIR__.'/../routes/channels.php',
    )
    ->withMiddleware(function (Middleware $middleware) {
        /**
         * Global Middleware (from Kernel::$middleware)
         */
        $middleware->append([
            TrustProxies::class,
            HandleCors::class,
            PreventRequestsDuringMaintenance::class,
            ValidatePostSize::class,
            TrimStrings::class,
            ConvertEmptyStringsToNull::class,
        ]);

        /**
         * Middleware Groups (from Kernel::$middlewareGroups)
         */
        $middleware->group('web', [
            EnsureApplicationKey::class,
            EncryptCookies::class,
            AddQueuedCookiesToResponse::class,
            StartSession::class,
            EnsureInstalled::class,
            SetLocale::class,
            ShareErrorsFromSession::class,
            VerifyCsrfToken::class,
            SubstituteBindings::class,
            AddLinkHeadersForPreloadedAssets::class,
        ]);

        $middleware->group('api', [
            // \Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,
            // Shared X-App-Key. Inert until a key is set in Settings -> API
            // Security, so this changes nothing for an install that ignores it.
            EnsureAppKey::class,
            ThrottleRequests::class.':api',
            SubstituteBindings::class,
        ]);

        /**
         * Middleware Aliases (from Kernel::$middlewareAliases)
         */
        $middleware->alias([
            'auth' => Authenticate::class,
            'XSS' => XSS::class,
            'AuthCheck' => AuthCheck::class,
            'auth.basic' => AuthenticateWithBasicAuth::class,
            'auth.session' => AuthenticateSession::class,
            'cache.headers' => SetCacheHeaders::class,
            'can' => Authorize::class,
            'guest' => RedirectIfAuthenticated::class,
            'password.confirm' => RequirePassword::class,
            'precognitive' => HandlePrecognitiveRequests::class,
            'signed' => ValidateSignature::class,
            'throttle' => ThrottleRequests::class,
            'verified' => EnsureEmailIsVerified::class,
            'hasPermission' => EnsurePermission::class,
            'installer.guest' => RedirectIfInstalled::class,
            'demo.readonly' => DenyDuringDemo::class,
        ]);
    })
    ->withExceptions(function (Exceptions $exceptions) {
        // You can configure exception handling here.
        // Example:
        // $exceptions->report(function (Throwable $e) {
        //     //
        // });
    })
    ->create();
