<?php

/*
|--------------------------------------------------------------------------
| Country Dial Codes
|--------------------------------------------------------------------------
|
| Used by the phone inputs on the website and the admin panel. Generated from
| the same list the mobile app's picker ships with (intl_phone_field), so the
| two cannot drift apart and produce different E.164 numbers for one country.
|
| Keyed by ISO 3166-1 alpha-2.
|
*/

return [
    'AF' => ['name' => 'Afghanistan', 'dial' => '93'],
    'AL' => ['name' => 'Albania', 'dial' => '355'],
    'DZ' => ['name' => 'Algeria', 'dial' => '213'],
    'AS' => ['name' => 'American Samoa', 'dial' => '1684'],
    'AD' => ['name' => 'Andorra', 'dial' => '376'],
    'AO' => ['name' => 'Angola', 'dial' => '244'],
    'AI' => ['name' => 'Anguilla', 'dial' => '1264'],
    'AQ' => ['name' => 'Antarctica', 'dial' => '672'],
    'AG' => ['name' => 'Antigua and Barbuda', 'dial' => '1268'],
    'AR' => ['name' => 'Argentina', 'dial' => '54'],
    'AM' => ['name' => 'Armenia', 'dial' => '374'],
    'AW' => ['name' => 'Aruba', 'dial' => '297'],
    'AU' => ['name' => 'Australia', 'dial' => '61'],
    'AT' => ['name' => 'Austria', 'dial' => '43'],
    'AZ' => ['name' => 'Azerbaijan', 'dial' => '994'],
    'BS' => ['name' => 'Bahamas', 'dial' => '1242'],
    'BH' => ['name' => 'Bahrain', 'dial' => '973'],
    'BD' => ['name' => 'Bangladesh', 'dial' => '880'],
    'BB' => ['name' => 'Barbados', 'dial' => '1246'],
    'BY' => ['name' => 'Belarus', 'dial' => '375'],
    'BE' => ['name' => 'Belgium', 'dial' => '32'],
    'BZ' => ['name' => 'Belize', 'dial' => '501'],
    'BJ' => ['name' => 'Benin', 'dial' => '229'],
    'BM' => ['name' => 'Bermuda', 'dial' => '1441'],
    'BT' => ['name' => 'Bhutan', 'dial' => '975'],
    'BO' => ['name' => 'Bolivia, Plurinational State of bolivia', 'dial' => '591'],
    'BA' => ['name' => 'Bosnia and Herzegovina', 'dial' => '387'],
    'BW' => ['name' => 'Botswana', 'dial' => '267'],
    'BV' => ['name' => 'Bouvet Island', 'dial' => '47'],
    'BR' => ['name' => 'Brazil', 'dial' => '55'],
    'IO' => ['name' => 'British Indian Ocean Territory', 'dial' => '246'],
    'BN' => ['name' => 'Brunei Darussalam', 'dial' => '673'],
    'BG' => ['name' => 'Bulgaria', 'dial' => '359'],
    'BF' => ['name' => 'Burkina Faso', 'dial' => '226'],
    'BI' => ['name' => 'Burundi', 'dial' => '257'],
    'KH' => ['name' => 'Cambodia', 'dial' => '855'],
    'CM' => ['name' => 'Cameroon', 'dial' => '237'],
    'IT' => ['name' => 'Campione d\'Italia', 'dial' => '41'],
    'CA' => ['name' => 'Canada', 'dial' => '1'],
    'KY' => ['name' => 'Cayman Islands', 'dial' => '345'],
    'CF' => ['name' => 'Central African Republic', 'dial' => '236'],
    'TD' => ['name' => 'Chad', 'dial' => '235'],
    'CL' => ['name' => 'Chile', 'dial' => '56'],
    'CN' => ['name' => 'China', 'dial' => '86'],
    'CX' => ['name' => 'Christmas Island', 'dial' => '61'],
    'CC' => ['name' => 'Cocos (Keeling) Islands', 'dial' => '61'],
    'CO' => ['name' => 'Colombia', 'dial' => '57'],
    'KM' => ['name' => 'Comoros', 'dial' => '269'],
    'CG' => ['name' => 'Congo', 'dial' => '242'],
    'CD' => ['name' => 'Congo, The Democratic Republic of the Congo', 'dial' => '243'],
    'CK' => ['name' => 'Cook Islands', 'dial' => '682'],
    'CR' => ['name' => 'Costa Rica', 'dial' => '506'],
    'HR' => ['name' => 'Croatia', 'dial' => '385'],
    'CU' => ['name' => 'Cuba', 'dial' => '53'],
    'CY' => ['name' => 'Cyprus', 'dial' => '357'],
    'CZ' => ['name' => 'Czech Republic', 'dial' => '420'],
    'CI' => ['name' => 'Côte d\'Ivoire', 'dial' => '225'],
    'DK' => ['name' => 'Denmark', 'dial' => '45'],
    'DJ' => ['name' => 'Djibouti', 'dial' => '253'],
    'DM' => ['name' => 'Dominica', 'dial' => '1767'],
    'DO' => ['name' => 'Dominican Republic', 'dial' => '1'],
    'EC' => ['name' => 'Ecuador', 'dial' => '593'],
    'EG' => ['name' => 'Egypt', 'dial' => '20'],
    'SV' => ['name' => 'El Salvador', 'dial' => '503'],
    'GQ' => ['name' => 'Equatorial Guinea', 'dial' => '240'],
    'ER' => ['name' => 'Eritrea', 'dial' => '291'],
    'EE' => ['name' => 'Estonia', 'dial' => '372'],
    'SZ' => ['name' => 'Eswatini', 'dial' => '268'],
    'ET' => ['name' => 'Ethiopia', 'dial' => '251'],
    'FK' => ['name' => 'Falkland Islands (Malvinas)', 'dial' => '500'],
    'FO' => ['name' => 'Faroe Islands', 'dial' => '298'],
    'FJ' => ['name' => 'Fiji', 'dial' => '679'],
    'FI' => ['name' => 'Finland', 'dial' => '358'],
    'FR' => ['name' => 'France', 'dial' => '33'],
    'GF' => ['name' => 'French Guiana', 'dial' => '594'],
    'PF' => ['name' => 'French Polynesia', 'dial' => '689'],
    'TF' => ['name' => 'French Southern Territories', 'dial' => '262'],
    'GA' => ['name' => 'Gabon', 'dial' => '241'],
    'GM' => ['name' => 'Gambia', 'dial' => '220'],
    'GE' => ['name' => 'Georgia', 'dial' => '995'],
    'DE' => ['name' => 'Germany', 'dial' => '49'],
    'GH' => ['name' => 'Ghana', 'dial' => '233'],
    'GI' => ['name' => 'Gibraltar', 'dial' => '350'],
    'GR' => ['name' => 'Greece', 'dial' => '30'],
    'GL' => ['name' => 'Greenland', 'dial' => '299'],
    'GD' => ['name' => 'Grenada', 'dial' => '1473'],
    'GP' => ['name' => 'Guadeloupe', 'dial' => '590'],
    'GU' => ['name' => 'Guam', 'dial' => '1671'],
    'GT' => ['name' => 'Guatemala', 'dial' => '502'],
    'GG' => ['name' => 'Guernsey', 'dial' => '44'],
    'GN' => ['name' => 'Guinea', 'dial' => '224'],
    'GW' => ['name' => 'Guinea-Bissau', 'dial' => '245'],
    'GY' => ['name' => 'Guyana', 'dial' => '592'],
    'HT' => ['name' => 'Haiti', 'dial' => '509'],
    'HM' => ['name' => 'Heard Island and Mcdonald Islands', 'dial' => '672'],
    'VA' => ['name' => 'Holy See (Vatican City State)', 'dial' => '379'],
    'HN' => ['name' => 'Honduras', 'dial' => '504'],
    'HK' => ['name' => 'Hong Kong', 'dial' => '852'],
    'HU' => ['name' => 'Hungary', 'dial' => '36'],
    'IS' => ['name' => 'Iceland', 'dial' => '354'],
    'IN' => ['name' => 'India', 'dial' => '91'],
    'ID' => ['name' => 'Indonesia', 'dial' => '62'],
    'IR' => ['name' => 'Iran, Islamic Republic of Persian Gulf', 'dial' => '98'],
    'IQ' => ['name' => 'Iraq', 'dial' => '964'],
    'IE' => ['name' => 'Ireland', 'dial' => '353'],
    'IM' => ['name' => 'Isle of Man', 'dial' => '44'],
    'IL' => ['name' => 'Israel', 'dial' => '972'],
    'JM' => ['name' => 'Jamaica', 'dial' => '1876'],
    'JP' => ['name' => 'Japan', 'dial' => '81'],
    'JE' => ['name' => 'Jersey', 'dial' => '44'],
    'JO' => ['name' => 'Jordan', 'dial' => '962'],
    'KZ' => ['name' => 'Kazakhstan', 'dial' => '7'],
    'KE' => ['name' => 'Kenya', 'dial' => '254'],
    'KI' => ['name' => 'Kiribati', 'dial' => '686'],
    'KP' => ['name' => 'Korea, Democratic People\'s Republic of Korea', 'dial' => '850'],
    'KR' => ['name' => 'Korea, Republic of South Korea', 'dial' => '82'],
    'KW' => ['name' => 'Kuwait', 'dial' => '965'],
    'KG' => ['name' => 'Kyrgyzstan', 'dial' => '996'],
    'LA' => ['name' => 'Laos', 'dial' => '856'],
    'LV' => ['name' => 'Latvia', 'dial' => '371'],
    'LB' => ['name' => 'Lebanon', 'dial' => '961'],
    'LS' => ['name' => 'Lesotho', 'dial' => '266'],
    'LR' => ['name' => 'Liberia', 'dial' => '231'],
    'LY' => ['name' => 'Libyan Arab Jamahiriya', 'dial' => '218'],
    'LI' => ['name' => 'Liechtenstein', 'dial' => '423'],
    'LT' => ['name' => 'Lithuania', 'dial' => '370'],
    'LU' => ['name' => 'Luxembourg', 'dial' => '352'],
    'MO' => ['name' => 'Macao', 'dial' => '853'],
    'MK' => ['name' => 'Macedonia', 'dial' => '389'],
    'MG' => ['name' => 'Madagascar', 'dial' => '261'],
    'MW' => ['name' => 'Malawi', 'dial' => '265'],
    'MY' => ['name' => 'Malaysia', 'dial' => '60'],
    'MV' => ['name' => 'Maldives', 'dial' => '960'],
    'ML' => ['name' => 'Mali', 'dial' => '223'],
    'MT' => ['name' => 'Malta', 'dial' => '356'],
    'MH' => ['name' => 'Marshall Islands', 'dial' => '692'],
    'MQ' => ['name' => 'Martinique', 'dial' => '596'],
    'MR' => ['name' => 'Mauritania', 'dial' => '222'],
    'MU' => ['name' => 'Mauritius', 'dial' => '230'],
    'YT' => ['name' => 'Mayotte', 'dial' => '262'],
    'MX' => ['name' => 'Mexico', 'dial' => '52'],
    'FM' => ['name' => 'Micronesia, Federated States of Micronesia', 'dial' => '691'],
    'MD' => ['name' => 'Moldova', 'dial' => '373'],
    'MC' => ['name' => 'Monaco', 'dial' => '377'],
    'MN' => ['name' => 'Mongolia', 'dial' => '976'],
    'ME' => ['name' => 'Montenegro', 'dial' => '382'],
    'MS' => ['name' => 'Montserrat', 'dial' => '1664'],
    'MA' => ['name' => 'Morocco', 'dial' => '212'],
    'MZ' => ['name' => 'Mozambique', 'dial' => '258'],
    'MM' => ['name' => 'Myanmar', 'dial' => '95'],
    'NA' => ['name' => 'Namibia', 'dial' => '264'],
    'NR' => ['name' => 'Nauru', 'dial' => '674'],
    'NP' => ['name' => 'Nepal', 'dial' => '977'],
    'NL' => ['name' => 'Netherlands', 'dial' => '31'],
    'NC' => ['name' => 'New Caledonia', 'dial' => '687'],
    'NZ' => ['name' => 'New Zealand', 'dial' => '64'],
    'NI' => ['name' => 'Nicaragua', 'dial' => '505'],
    'NE' => ['name' => 'Niger', 'dial' => '227'],
    'NG' => ['name' => 'Nigeria', 'dial' => '234'],
    'NU' => ['name' => 'Niue', 'dial' => '683'],
    'NF' => ['name' => 'Norfolk Island', 'dial' => '672'],
    'MP' => ['name' => 'Northern Mariana Islands', 'dial' => '1670'],
    'NO' => ['name' => 'Norway', 'dial' => '47'],
    'OM' => ['name' => 'Oman', 'dial' => '968'],
    'PK' => ['name' => 'Pakistan', 'dial' => '92'],
    'PW' => ['name' => 'Palau', 'dial' => '680'],
    'PS' => ['name' => 'Palestinian Territory, Occupied', 'dial' => '970'],
    'PA' => ['name' => 'Panama', 'dial' => '507'],
    'PG' => ['name' => 'Papua New Guinea', 'dial' => '675'],
    'PY' => ['name' => 'Paraguay', 'dial' => '595'],
    'PE' => ['name' => 'Peru', 'dial' => '51'],
    'PH' => ['name' => 'Philippines', 'dial' => '63'],
    'PN' => ['name' => 'Pitcairn', 'dial' => '64'],
    'PL' => ['name' => 'Poland', 'dial' => '48'],
    'PT' => ['name' => 'Portugal', 'dial' => '351'],
    'PR' => ['name' => 'Puerto Rico', 'dial' => '1939'],
    'QA' => ['name' => 'Qatar', 'dial' => '974'],
    'RE' => ['name' => 'Reunion', 'dial' => '262'],
    'RO' => ['name' => 'Romania', 'dial' => '40'],
    'RU' => ['name' => 'Russia', 'dial' => '7'],
    'RW' => ['name' => 'Rwanda', 'dial' => '250'],
    'BL' => ['name' => 'Saint Barthelemy', 'dial' => '590'],
    'SH' => ['name' => 'Saint Helena, Ascension and Tristan Da Cunha', 'dial' => '290'],
    'KN' => ['name' => 'Saint Kitts and Nevis', 'dial' => '1869'],
    'LC' => ['name' => 'Saint Lucia', 'dial' => '1758'],
    'MF' => ['name' => 'Saint Martin', 'dial' => '590'],
    'PM' => ['name' => 'Saint Pierre and Miquelon', 'dial' => '508'],
    'VC' => ['name' => 'Saint Vincent and the Grenadines', 'dial' => '1784'],
    'WS' => ['name' => 'Samoa', 'dial' => '685'],
    'SM' => ['name' => 'San Marino', 'dial' => '378'],
    'ST' => ['name' => 'Sao Tome and Principe', 'dial' => '239'],
    'SA' => ['name' => 'Saudi Arabia', 'dial' => '966'],
    'SN' => ['name' => 'Senegal', 'dial' => '221'],
    'RS' => ['name' => 'Serbia', 'dial' => '381'],
    'SC' => ['name' => 'Seychelles', 'dial' => '248'],
    'SL' => ['name' => 'Sierra Leone', 'dial' => '232'],
    'SG' => ['name' => 'Singapore', 'dial' => '65'],
    'SK' => ['name' => 'Slovakia', 'dial' => '421'],
    'SI' => ['name' => 'Slovenia', 'dial' => '386'],
    'SB' => ['name' => 'Solomon Islands', 'dial' => '677'],
    'SO' => ['name' => 'Somalia', 'dial' => '252'],
    'ZA' => ['name' => 'South Africa', 'dial' => '27'],
    'GS' => ['name' => 'South Georgia and the South Sandwich Islands', 'dial' => '500'],
    'SS' => ['name' => 'South Sudan', 'dial' => '211'],
    'ES' => ['name' => 'Spain', 'dial' => '34'],
    'LK' => ['name' => 'Sri Lanka', 'dial' => '94'],
    'SD' => ['name' => 'Sudan', 'dial' => '249'],
    'SR' => ['name' => 'Suriname', 'dial' => '597'],
    'SJ' => ['name' => 'Svalbard and Jan Mayen', 'dial' => '47'],
    'SE' => ['name' => 'Sweden', 'dial' => '46'],
    'CH' => ['name' => 'Switzerland', 'dial' => '41'],
    'SY' => ['name' => 'Syrian Arab Republic', 'dial' => '963'],
    'TW' => ['name' => 'Taiwan', 'dial' => '886'],
    'TJ' => ['name' => 'Tajikistan', 'dial' => '992'],
    'TZ' => ['name' => 'Tanzania, United Republic of Tanzania', 'dial' => '255'],
    'TH' => ['name' => 'Thailand', 'dial' => '66'],
    'TL' => ['name' => 'Timor-Leste', 'dial' => '670'],
    'TG' => ['name' => 'Togo', 'dial' => '228'],
    'TK' => ['name' => 'Tokelau', 'dial' => '690'],
    'TO' => ['name' => 'Tonga', 'dial' => '676'],
    'TT' => ['name' => 'Trinidad and Tobago', 'dial' => '1868'],
    'TN' => ['name' => 'Tunisia', 'dial' => '216'],
    'TR' => ['name' => 'Turkey', 'dial' => '90'],
    'TM' => ['name' => 'Turkmenistan', 'dial' => '993'],
    'TC' => ['name' => 'Turks and Caicos Islands', 'dial' => '1649'],
    'TV' => ['name' => 'Tuvalu', 'dial' => '688'],
    'UG' => ['name' => 'Uganda', 'dial' => '256'],
    'UA' => ['name' => 'Ukraine', 'dial' => '380'],
    'AE' => ['name' => 'United Arab Emirates', 'dial' => '971'],
    'GB' => ['name' => 'United Kingdom', 'dial' => '44'],
    'US' => ['name' => 'United States', 'dial' => '1'],
    'UY' => ['name' => 'Uruguay', 'dial' => '598'],
    'UZ' => ['name' => 'Uzbekistan', 'dial' => '998'],
    'VU' => ['name' => 'Vanuatu', 'dial' => '678'],
    'VE' => ['name' => 'Venezuela, Bolivarian Republic of Venezuela', 'dial' => '58'],
    'VN' => ['name' => 'Vietnam', 'dial' => '84'],
    'VG' => ['name' => 'Virgin Islands, British', 'dial' => '1284'],
    'VI' => ['name' => 'Virgin Islands, U.S.', 'dial' => '1340'],
    'WF' => ['name' => 'Wallis and Futuna', 'dial' => '681'],
    'YE' => ['name' => 'Yemen', 'dial' => '967'],
    'ZM' => ['name' => 'Zambia', 'dial' => '260'],
    'AX' => ['name' => 'Åland Islands', 'dial' => '358'],
];
